name: presence_sensor_app
description: "Presence Sensor BLE configuration app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # BLE
  flutter_blue_plus: ^1.35.3

  # HTTP для скачивания прошивки и проверки обновлений
  http: ^1.4.0

  # Локальное хранилище (список устройств, настройки)
  shared_preferences: ^2.5.3

  # Разрешения (bluetooth, location)
  permission_handler: ^11.4.0

  # Индикатор прогресса
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
